# Useful links

This page provides links to online resources that may be useful when working with Quarto or this template.

## Quarto

- [Quarto guide](https://quarto.org/docs/guide/)
- [Using `R` with Quarto](https://quarto.org/docs/computations/r.html)

### Markdown

- [Quarto Markdown basics](https://quarto.org/docs/authoring/markdown-basics.html)
- [`kableExtra` documentation](https://www.rdocumentation.org/packages/kableExtra/versions/1.4.0)
- [`RMarkdown` cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/)

## `R`

- [Programming with `R` (Carpentries)](https://swcarpentry.github.io/r-novice-inflammation/)
- [`R` for Reproducible Scientific Analysis (Carpentries)](https://swcarpentry.github.io/r-novice-gapminder/)

### Data processing

- [`readr` documentation](https://readr.tidyverse.org/)
- [`dplyr` documentation](https://dplyr.tidyverse.org/)
- [`tidyr` documentation](https://tidyr.tidyverse.org/)
- [`stringr` documentation](https://stringr.tidyverse.org/)
- [`lubridate` documentation](https://lubridate.tidyverse.org/)

### Data Visualisation

- [`ggplot2` documentation](https://ggplot2.tidyverse.org/reference/)
- [`ggally` documentation](https://ggobi.github.io/ggally/reference/index.html)
- [`ggpubr` documentation](https://rpkgs.datanovia.com/ggpubr/index.html)

### `Shiny`

- [`Shiny` documentation](https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/)

## `RStudio`

- [`RStudio` Getting Started](https://docs.posit.co/ide/user/ide/get-started/)
- [`RStudio` tutorial (DataCamp)](https://www.datacamp.com/tutorial/r-studio-tutorial)
- [Using `git` from `RStudio` (Carpentries)](https://opsis.eci.ox.ac.uk/swc-git-novice/14-supplemental-rstudio.html)

### `Shiny`

- [`r-`shinylive` documentation](https://posit-dev.github.io/r-shinylive/)
- [`shinylive` documentation](https://shiny.posit.co/py/get-started/shinylive.html)

### `WebR`

- [`WebR` documentation](https://docs.r-wasm.org/webr/latest/)

## Version Control with `git` and GitHub

### `git`

- [Version control with `git` (Carpentries)](https://swcarpentry.github.io/git-novice/)
- [About `git` (GitHub)](https://docs.github.com/en/get-started/using-git/about-git)
- [Using `git` with `RStudio`](https://r-bio.github.io/intro-git-rstudio/)

### GitHub

- [Getting started with GitHub](https://docs.github.com/en/get-started)
- [Creating an account on GitHub](https://docs.github.com/en/get-started/start-your-journey/creating-an-account-on-github)
- [Using `git`/GitHub with `R`](https://rfortherestofus.com/2021/02/how-to-use-git-github-with-r/)

## Cheatsheets

- [Quarto/RMarkdown cheatsheet](https://posit.co/wp-content/uploads/2022/10/rmarkdown-1.pdf)
- [`readr` cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-import.pdf)
- [`dplyr` cheatsheet](https://github.com/rstudio/cheatsheets/blob/main/data-transformation.pdf)
- [`tidyr` cheatsheet](https://github.com/rstudio/cheatsheets/blob/master/tidyr.pdf)
- [`stringr` cheatsheet](https://github.com/rstudio/cheatsheets/blob/main/strings.pdf)
- [`lubridate` cheatsheet](https://rawgit.com/rstudio/cheatsheets/main/lubridate.pdf)
- [`ggplot2` cheatsheet](https://posit.co/wp-content/uploads/2022/10/data-visualization-1.pdf)
- [`Shiny` cheatsheet](https://github.com/rstudio/cheatsheets/raw/main/shiny.pdf)
- [`git` cheatsheet](https://education.github.com/git-cheat-sheet-education.pdf)
- [GitHub cheatsheet](https://lahirumw.github.io/2025-01-26-github-cheat-sheet/)