# Embedding video files

This page demonstrates how to embed video into a Quarto webpage. This is a native capability of Quarto, and requires no extensions to be installed.

- [Quarto video embedding documentation](https://quarto.org/docs/authoring/videos.html)

## Embedding a video

To embed a video, use the `{{{< video >}}}` shortcode. You can embed local files or URLs of online videos:

```markdown
{{{< video local-video-file.mp4 >}}}

{{{< video URL_TO_VIDEO >}}}
```

### Local file

::: { .callout-tip }
This template provides an `assets/videos` folder, which can be used for adding video files to the repository.
:::

::: { .panel-tabset }

## Appearance

{{< video assets/videos/template-tutorial-video-1a.mp4 >}}

## Markdown

```markdown
{{{< video assets/videos/template-tutorial-video-1a.mp4 >}}}
```

:::

### Remote video file

::: { .panel-tabset }

## Appearance

{{< video https://youtu.be/dQw4w9WgXcQ?si=_BZIcKuz9U91pGqB >}}

## Markdown

```markdown
{{{< video https://youtu.be/dQw4w9WgXcQ?si=_BZIcKuz9U91pGqB >}}}
```

:::

### Cross-referencing videos

To use cross-references with videos, wrap the video in a `div` using three colons, as in the example below. They can then be referenced using the usual `@fig-label` method.

::: { .panel-tabset }

## Appearance

::: {#fig-example-1}

{{< video assets/videos/template-tutorial-video-1a.mp4 >}}

This is an example video with cross-referencing (and a legend!)

:::

And it's cross-referenced like this (@fig-example-1).

## Markdown

```markdown
::: {#fig-example-1}

{{{< video assets/videos/template-tutorial-video-1a.mp4 >}}}

This is an example video with cross-referencing (and a legend!)

:::

And it's cross-referenced like this (@fig-example-1).
```

:::